// Package nginx renders and manages the devbox-owned nginx config that lives
// under ~/.exe-devbox/nginx/conf.d/. The system nginx loads it via a one-time
// include shim at /etc/nginx/conf.d/devbox.conf.
//
// Design:
//   - 00-devbox-base.conf: a WS upgrade map + a catch-all default_server. This
//     is regenerated deterministically by setup.
//   - <project>.conf: one server block per project, written by `devbox new`.
//     A project may have multiple domains (space-separated server_name).
//   - Reload = `nginx -t && systemctl reload nginx` (works; no Caddy admin-off quirk).
package nginx

import (
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
)

// BaseConf renders 00-devbox-base.conf: the WS upgrade map and a catch-all
// server on the devbox port. Every project server also listens on the same
// port and uses server_name to disambiguate; the base is the default_server.
func BaseConf(port int) string {
	return fmt.Sprintf(`# managed by devbox — do not edit by hand (regenerated by `+"`devbox setup`"+`)
# WebSocket / Vite HMR upgrade mapping, shared by all project server blocks.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# Catch-all: unknown Host -> 404. (default_server on the devbox port.)
server {
    listen %d default_server;
    listen [::]:%d default_server;
    server_name _;
    return 404;
}
`, port, port)
}

// ProjectSpec describes one project server block.
type ProjectSpec struct {
	// Domains are the public FQDN(s) this block answers. More than one
	// (e.g. devbox.nesin.io + devbox.ashiknesin.com) shares a backend.
	Domains []string
	Project string // route name -> <project>.localhost (only for backend=portless)
	Backend string // "portless" or "loopback:<port>"
}

// ProjectConf renders a single <project>.conf server block.
//   - portless: proxy_pass :8888 + rewrite Host to <project>.localhost
//   - loopback:<port>: proxy_pass 127.0.0.1:<port>, keep real Host
//
// Both carry WS upgrade headers so Vite HMR works through the chain.
func ProjectConf(port int, s ProjectSpec) string {
	var upstream, hostHeader string
	switch {
	case s.Backend == "portless" || s.Backend == "":
		upstream = "http://127.0.0.1:8888"
		hostHeader = s.Project + ".localhost"
	case strings.HasPrefix(s.Backend, "loopback:"):
		upstream = "http://127.0.0.1:" + strings.TrimPrefix(s.Backend, "loopback:")
		hostHeader = "$host"
	default:
		upstream = "http://127.0.0.1:8888"
		hostHeader = s.Project + ".localhost"
	}

	domains := strings.Join(s.Domains, " ")

	return fmt.Sprintf(`# managed by devbox — project: %s
server {
    listen %d;
    listen [::]:%d;
    server_name %s;

    location / {
        proxy_pass %s;
        proxy_set_header Host %s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket / Vite HMR upgrade
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
    }
}
`, s.Project, port, port, domains, upstream, hostHeader)
}

// IncludeShim is the one-time /etc/nginx/conf.d/devbox.conf that pulls in the
// user-owned conf.d dir. nginx doesn't expand ~, so the home path is resolved
// at write time by setup.
func IncludeShim(confDir string) string {
	return fmt.Sprintf("# managed by devbox — include user-owned project configs\ninclude %s;\n",
		filepath.Join(confDir, "*.conf"))
}

// Test runs `nginx -t` (config syntax + include validation). Returns combined output.
func Test() ([]byte, error) {
	return exec.Command("nginx", "-t").CombinedOutput()
}

// Reload validates then reloads nginx. Returns validation output + reload error.
func Reload() ([]byte, error) {
	out, err := Test()
	if err != nil {
		return out, fmt.Errorf("nginx -t failed: %w", err)
	}
	reloadErr := exec.Command("systemctl", "reload", "nginx").Run()
	return out, reloadErr
}
