// Package nginx renders and manages the exebox-owned nginx config that lives
// under ~/.exebox/nginx/conf.d/. The system nginx loads it via a one-time
// include shim at /etc/nginx/conf.d/exebox.conf.
//
// Design:
//   - 00-exebox-base.conf: a WS upgrade map + a catch-all default_server. This
//     is regenerated deterministically by setup.
//   - <project>.conf: one server block per project, written by `exebox new`.
//     A project may have multiple domains (space-separated server_name).
//   - Reload = `nginx -t && systemctl reload nginx` (works; no Caddy admin-off quirk).
package nginx

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/ashiknesin/exebox/internal/system"
)

// BaseConf renders 00-exebox-base.conf: the WS upgrade map and a catch-all
// server on the exebox port. Every project server also listens on the same
// port and uses server_name to disambiguate; the base is the default_server.
func BaseConf(port int) string {
	return fmt.Sprintf(`# managed by exebox — do not edit by hand (regenerated by `+"`exebox setup`"+`)
# WebSocket / Vite HMR upgrade mapping, shared by all project server blocks.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# Catch-all: unknown Host -> 404. (default_server on the exebox port.)
server {
    listen %d default_server;
    listen [::]:%d default_server;
    server_name _;
    return 404;
}
`, port, port)
}

// ProjectSpec describes one project server block.
type ProjectSpec struct {
	// Domains are the public FQDN(s) this block answers. More than one
	// (e.g. devbox.nesin.io + devbox.ashiknesin.com) shares a backend.
	Domains       []string
	Project       string // route name -> <project>.localhost (only for backend=portless)
	Backend       string // "portless" or "loopback:<port>"
	PortlessPort  int    // portless daemon port (for backend=portless); 0 = 8888
}

// ProjectConf renders a single <project>.conf server block.
//   - portless: proxy_pass :<portlessPort> + rewrite Host to <project>.localhost
//   - loopback:<port>: proxy_pass 127.0.0.1:<port>, keep real Host
//
// Both carry WS upgrade headers so Vite HMR works through the chain.
func ProjectConf(port int, s ProjectSpec) string {
	portlessPort := s.PortlessPort
	if portlessPort == 0 {
		portlessPort = 8888
	}
	var upstream, hostHeader string
	switch {
	case s.Backend == "portless" || s.Backend == "":
		upstream = fmt.Sprintf("http://127.0.0.1:%d", portlessPort)
		hostHeader = s.Project + ".localhost"
	case strings.HasPrefix(s.Backend, "loopback:"):
		upstream = "http://127.0.0.1:" + strings.TrimPrefix(s.Backend, "loopback:")
		hostHeader = "$host"
	default:
		upstream = fmt.Sprintf("http://127.0.0.1:%d", portlessPort)
		hostHeader = s.Project + ".localhost"
	}

	domains := strings.Join(s.Domains, " ")

	return fmt.Sprintf(`# managed by exebox — project: %s
server {
    listen %d;
    listen [::]:%d;
    server_name %s;

    location / {
        proxy_pass %s;
        proxy_set_header Host %s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket / Vite HMR upgrade
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
    }
}
`, s.Project, port, port, domains, upstream, hostHeader)
}

// IncludeShim is the one-time /etc/nginx/conf.d/exebox.conf that pulls in the
// user-owned conf.d dir. nginx doesn't expand ~, so the home path is resolved
// at write time by setup.
func IncludeShim(confDir string) string {
	return fmt.Sprintf("# managed by exebox — include user-owned project configs\ninclude %s;\n",
		filepath.Join(confDir, "*.conf"))
}

// Test runs `nginx -t` (config syntax + include validation). Run as root so
// it can verify the pid/paths in nginx.conf (non-root `nginx -t` fails on
// /run/nginx.pid permission even when config is valid).
func Test() ([]byte, error) {
	return system.AsRoot("nginx", "-t").CombinedOutput()
}

// Reload validates then reloads nginx. Returns validation output + reload error.
// We retry the reload a couple times because `systemctl reload` can return just
// before workers finish loading the new config, causing a brief stale-routing
// window that surprises tests run immediately after.
func Reload() ([]byte, error) {
	out, err := Test()
	if err != nil {
		return out, fmt.Errorf("nginx -t failed: %w", err)
	}
	var reloadErr error
	for attempt := 0; attempt < 3; attempt++ {
		reloadErr = system.AsRoot("systemctl", "reload", "nginx").Run()
		if reloadErr == nil {
			time.Sleep(200 * time.Millisecond) // let workers settle
			return out, nil
		}
		time.Sleep(300 * time.Millisecond)
	}
	return out, reloadErr
}
